# Backend service
- type: web
  name: alphora-backend
  env: node
  plan: free    # change from "starter" to "free"
  branch: main
  rootDir: Catalog/backend
  buildCommand: npm install
  startCommand: node server.js
